services:
  backend:
    image: raizergr/cloud_storage_backend
    env_file: .env
    ports:
      - 3000:8080
    depends_on:
      - postgres

  frontend:
    image: raizergr/cloud_storage_frontend
    ports:
      - 8080:8080
    depends_on:
      - backend
    env_file: .env

  postgres:
    image: postgres:16
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file: .env

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes: 
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning --requirepass 12345
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:5000'
    volumes:
      - redis_insight_data:/db

volumes:
  pg_data:
  redis_data:
  redis_insight_data: