services:
  backend:
    build: ./backend
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
    ports:
      - 3000:8080
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    environment:
      - HOST=51.250.39.148
    ports:
      - 8080:8080
    depends_on:
      - backend

  postgres:
    image: postgres:16
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
  
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes: 
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning --requirepass 12345

  redis_insight:
    image: redis/redisinsight:latest
    ports:
      - '5540:5540'
    volumes:
      - redis_insight_data:/data

volumes:
  pg_data: