spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: create
  session:
      timeout: 1800
  messages:
    basename: messages
  data:
    redis:
      host: redis
      port: 6379
      password: 12345
logging:
  level:
    root: INFO
    org.springframework: DEBUG
    com.yourpackage: DEBUG
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
