spring:
  application:
    name: Cloud-File-Storage
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: false
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: create
  session:
      timeout: 1800
  messages:
    basename: messages
  data:
    redis:
      host: redis
      port: 6379
      password: 12345
  liquibase:
    change-log: db/changelog/main-changelog.xml
  servlet:
    multipart:
      max-file-size: 120MB
      max-request-size: 120MB
      resolve-lazily: false
server:
  tomcat:
    max-swallow-size: -1
minio:
  host: ${MINIO_HOST:minio}
  port: ${MINIO_PORT:9000}
  login: ${MINIO_LOGIN:minioadmin}
  password: ${MINIO_PASSWORD:minioadmin}


